SELECT          
                SESSION_INFO_DIM_VW.CLIENT_USER_AGENT
        ,       CASE
                   WHEN CLIENT_USER_AGENT LIKE '%IPAD%' THEN 'iPad'
                   WHEN CLIENT_USER_AGENT LIKE '%IPHONE%' THEN 'iPhone'
                   WHEN CLIENT_USER_AGENT LIKE '%ANDROID%' THEN 'Android'
                   WHEN CLIENT_USER_AGENT LIKE '%MAC OS X%' THEN 'OS X'
                   WHEN CLIENT_USER_AGENT LIKE '%X11%' THEN 'Linux'
                   WHEN CLIENT_USER_AGENT LIKE '%WINDOWS NT 10.0%' THEN 'Windows 10'
                   WHEN CLIENT_USER_AGENT LIKE '%WINDOWS NT 6.3%' THEN 'Windows 8.1'
                   WHEN CLIENT_USER_AGENT LIKE '%WINDOWS NT 6.2%' THEN 'Windows 8'
                   WHEN CLIENT_USER_AGENT LIKE '%WINDOWS NT 6.1%' THEN 'Windows 7'
                   WHEN CLIENT_USER_AGENT LIKE '%WINDOWS NT 6.0%' THEN 'Windows Vista'
                   WHEN CLIENT_USER_AGENT LIKE '%WINDOWS NT 5.2%' THEN 'Windows Server 2003; Windows XP x64 Edition'
                   WHEN CLIENT_USER_AGENT LIKE '%WINDOWS NT 5.1%' THEN 'Windows XP'
                   WHEN CLIENT_USER_AGENT LIKE '%WINDOWS NT 5.0%' THEN 'Windows 2000'
                   WHEN CLIENT_USER_AGENT LIKE '%WINDOWS NT 4.0%' THEN 'Microsoft Windows NT 4.0'
                   WHEN CLIENT_USER_AGENT LIKE '%WINDOWS 9' THEN 'Windows 95/98/Millenium'
                   WHEN CLIENT_USER_AGENT LIKE '%WINDOWS CE' THEN 'Windows CE'
                   ELSE 'Other'
                END                                     OS
        ,       CASE
                   WHEN CLIENT_USER_AGENT LIKE '%CHROME%' THEN 'Chrome'
                   WHEN CLIENT_USER_AGENT LIKE '%SAFARI%' THEN 'Safari'
                   WHEN CLIENT_USER_AGENT LIKE '%FIREFOX%' THEN 'Firefox'
                   WHEN CLIENT_USER_AGENT LIKE '%MSIE 7%' THEN 'IE7'
                   WHEN CLIENT_USER_AGENT LIKE '%MSIE 8%' THEN 'IE8'
                   WHEN CLIENT_USER_AGENT LIKE '%MSIE 9%' THEN 'IE9'
                   WHEN CLIENT_USER_AGENT LIKE '%MSIE 10%' THEN 'IE10'
                   WHEN CLIENT_USER_AGENT LIKE '%RV:11%' THEN 'IE11'
                   ELSE 'Other'
                END                                     BROWSER
--        ,       CASE
--                    WHEN CLIENT_USER_AGENT LIKE '%FIREFOX/%'    THEN LEFT(RIGHT(CLIENT_USER_AGENT + ' ', CHAR_LENGTH(CLIENT_USER_AGENT + ' ') - INSTR(CLIENT_USER_AGENT + ' ','FIREFOX/') - 6), CHARINDEX(' ', RIGHT(CLIENT_USER_AGENT + ' ', LEN(CLIENT_USER_AGENT + ' ') - CHARINDEX('FIREFOX/', CLIENT_USER_AGENT + ' ') - 6)) - 1)
----                    WHEN CLIENT_USER_AGENT LIKE '%CHROME/%'     THEN LEFT(RIGHT(CLIENT_USER_AGENT, LEN(CLIENT_USER_AGENT) - CHARINDEX('CHROME/', CLIENT_USER_AGENT) - 6), CHARINDEX(' ', RIGHT(CLIENT_USER_AGENT, LEN(CLIENT_USER_AGENT) - CHARINDEX('CHROME/', CLIENT_USER_AGENT) - 6)) - 1)
----                    WHEN CLIENT_USER_AGENT LIKE '%MSIE %'       THEN LEFT(RIGHT(CLIENT_USER_AGENT + ';', LEN(CLIENT_USER_AGENT + ';') - CHARINDEX('MSIE ', CLIENT_USER_AGENT + ';') - 4), CHARINDEX(';', RIGHT(CLIENT_USER_AGENT + ';', LEN(CLIENT_USER_AGENT + ';') - CHARINDEX('MSIE ', CLIENT_USER_AGENT + ';') - 4)) - 1)
----                    WHEN CLIENT_USER_AGENT LIKE '%MSIE+%'       THEN LEFT(RIGHT(CLIENT_USER_AGENT + ';', LEN(CLIENT_USER_AGENT + ';') - CHARINDEX('MSIE+', CLIENT_USER_AGENT + ';') - 4), CHARINDEX(';', RIGHT(CLIENT_USER_AGENT + ';', LEN(CLIENT_USER_AGENT + ';') - CHARINDEX('MSIE+', CLIENT_USER_AGENT + ';') - 4)) - 1)
----                    WHEN CLIENT_USER_AGENT LIKE '%IPHONE%' AND CLIENT_USER_AGENT LIKE '%VERSION/%' 
----                                                                THEN LEFT(RIGHT(CLIENT_USER_AGENT, LEN(CLIENT_USER_AGENT) - CHARINDEX('VERSION/', CLIENT_USER_AGENT) - 7), CHARINDEX(' ', RIGHT(CLIENT_USER_AGENT, LEN(CLIENT_USER_AGENT) - CHARINDEX('VERSION/', CLIENT_USER_AGENT) - 7)) - 1)
----                    WHEN CLIENT_USER_AGENT LIKE '%IPAD%' AND CLIENT_USER_AGENT LIKE '%VERSION/%' 
----                                                                THEN LEFT(RIGHT(CLIENT_USER_AGENT, LEN(CLIENT_USER_AGENT) - CHARINDEX('VERSION/', CLIENT_USER_AGENT) - 7), CHARINDEX(' ', RIGHT(CLIENT_USER_AGENT, LEN(CLIENT_USER_AGENT) - CHARINDEX('VERSION/', CLIENT_USER_AGENT) - 7)) - 1)
----                    WHEN CLIENT_USER_AGENT LIKE '%OPERA%'       THEN LEFT(RIGHT(CLIENT_USER_AGENT + ' ', LEN(CLIENT_USER_AGENT + ' ') - CHARINDEX('OPERA/', CLIENT_USER_AGENT + ' ') - 4), CHARINDEX(' ', RIGHT(CLIENT_USER_AGENT + ' ', LEN(CLIENT_USER_AGENT + ' ') - CHARINDEX('OPERA/', CLIENT_USER_AGENT + ' ') - 4)) - 1)
----                    WHEN CLIENT_USER_AGENT LIKE '%BLACKBERRY%' AND CLIENT_USER_AGENT LIKE '%VERSION/%' 
----                                                                THEN LEFT(RIGHT(CLIENT_USER_AGENT, LEN(CLIENT_USER_AGENT) - CHARINDEX('VERSION/', CLIENT_USER_AGENT) - 7), CHARINDEX(' ', RIGHT(CLIENT_USER_AGENT, LEN(CLIENT_USER_AGENT) - CHARINDEX('VERSION/', CLIENT_USER_AGENT) - 7)) - 1)
----                    WHEN CLIENT_USER_AGENT LIKE '%BLACKBERRY%'  THEN RIGHT(LEFT(CLIENT_USER_AGENT + ' ', CHARINDEX(' ', CLIENT_USER_AGENT + ' ') - 1), LEN(LEFT(CLIENT_USER_AGENT + ' ', CHARINDEX(' ', CLIENT_USER_AGENT + ' ') - 1)) - CHARINDEX('/', LEFT(CLIENT_USER_AGENT + ' ', CHARINDEX(' ', CLIENT_USER_AGENT + ' ') - 1)))
----                    WHEN CLIENT_USER_AGENT LIKE '%ANDROID%'     THEN LEFT(RIGHT(CLIENT_USER_AGENT + ';', LEN(CLIENT_USER_AGENT + ';') - CHARINDEX('ANDROID ', CLIENT_USER_AGENT + ';') - 7), CHARINDEX(';', RIGHT(CLIENT_USER_AGENT + ';', LEN(CLIENT_USER_AGENT + ';') - CHARINDEX('ANDROID ', CLIENT_USER_AGENT + ';') - 7)) - 1)
----                    WHEN CLIENT_USER_AGENT LIKE '%SAFARI%' AND CLIENT_USER_AGENT LIKE '%VERSION/%' 
----                                                                THEN LEFT(RIGHT(CLIENT_USER_AGENT, LEN(CLIENT_USER_AGENT) - CHARINDEX('VERSION/', CLIENT_USER_AGENT) - 7), CHARINDEX(' ', RIGHT(CLIENT_USER_AGENT, LEN(CLIENT_USER_AGENT) - CHARINDEX('VERSION/', CLIENT_USER_AGENT) - 7)) - 1)
--                    WHEN CLIENT_USER_AGENT LIKE '%BOT%'         THEN '0.0'
--                    WHEN CLIENT_USER_AGENT LIKE '%HTTP://%'     THEN '0.0'
--                    WHEN CLIENT_USER_AGENT LIKE '%WWW.%'        THEN '0.0'
--                    WHEN CLIENT_USER_AGENT LIKE '%WGET%'        THEN '0.0'
--                    WHEN CLIENT_USER_AGENT LIKE '%CURL%'        THEN '0.0'
--                    WHEN CLIENT_USER_AGENT LIKE '%URLLIB%'      THEN '0.0'
--                    ELSE '0.0'
--                END                                     VERSION
FROM            MART.SESSION_INFO_DIM_VW